env: "local"
storage_conn: "host=localhost port=5432 user=postgres password=mysecretpassword dbname=postgres sslmode=disable timezone=GMT-7 connect_timeout=5"
http_server:
  address: "localhost:8000"
  timeout: 4s
  idle_timeout: 60s
  email: email
  password: password
